### ISSUE TITLE
关于谷歌浏览器下不兼容问题

### ISSUE THREAD

**Issue by qinmi352387597** [murongqimiao/DAGBoard#1]
发现在谷歌浏览器下连线计算目标节点有错误。

**Comment by murongqimiao** [comment]
hello老铁, 能不能提供浏览器, 设备,跟问题截图什么的.
周日改了一波foreignObject导致的定位异常问题, 在safari跟chrome的测试通过.
-------------------
虽然内容浅显,  我还是会维护到底的, 放心沟通 : )

**Comment by murongqimiao** [comment]
> 发现在谷歌浏览器下连线计算目标节点有错误。

这个问题我在win系统上复现了, 表现是hover的时候状态丢失,绿色区域闪烁, 无法成功触发连线.等修复后艾特你. 谢谢提出的bug.

**Comment by qinmi352387597** [comment]
我也是第一次接触绘制图形的开发，你算是我的前辈了。
学习ing。

**Comment by qinmi352387597** [comment]
<span class="space" @mousemove="linkEnd(i, nth)"></span> 
将mouseupdown事件替换为mousemove即可

**Comment by murongqimiao** [comment]
Hi 兄嘚 ! 最近业务比较忙没有处理这个项目的问题,这里说声抱歉~  刚刚发现foreignObject在新版chrome里默认overflow: hidden导致显示不全, 刚刚fix掉了这个问题, 如果这个问题依然存在, 烦请告知一声,谢谢~
