### ISSUE TITLE
谷歌浏览器下锚点显示不全

### ISSUE THREAD

**Issue by zlpcrmm** [murongqimiao/DAGBoard#2]
谷歌浏览器中hover到锚点上拖动连线时锚点只显示了一半，另一半遮挡住了，在Safari浏览器上正常，你线上的demo也是一样，希望能看一下

**Comment by murongqimiao** [comment]
> 谷歌浏览器中hover到锚点上拖动连线时锚点只显示了一半，另一半遮挡住了，在Safari浏览器上正常，你线上的demo也是一样，希望能看一下

这个问题昨天定位了一下,原因是chrome里foreignObject默认改成了overflow: hidden.所以重写overflow: inherit即可~

如果这个问题没有得到解决, 敬请联系,谢谢~
