### ISSUE TITLE
请教一下，每个节点在初始化的时候如何设置xy的值保证图形美观

### ISSUE THREAD

**Issue by shuangbofu** [murongqimiao/DAGBoard#3]
能保证节点连线之间尽量不相交

**Comment by murongqimiao** [comment]
每个节点单位都是可以自由拖动的, 拖动到指定点跟后台交互一下节点的最新信息进行保存,所以初始节点的位置不是很重要吧...
借鉴了阿里云机器学习平台的样式, 有条件的话可以去阿里云机器学习平台看一看,试一试大平台的成品,充五块钱能一直玩hhhhh

**Comment by murongqimiao** [comment]
> 能保证节点连线之间尽量不相交

最近跟数模组合作,  总结一下, 相同层级的节点y轴基本保持相同即可, 相同层级的节点, 按照序数, 依次 + 100像素左右即可.
