### ISSUE TITLE
推拽节点 鼠标移出 视图范围，MouseUp 事件 失效

### ISSUE THREAD

**Issue by 763139102** [murongqimiao/DAGBoard#5]
有时间看看这个问题

**Comment by 763139102** [comment]
![image](https://user-images.githubusercontent.com/25519902/59318876-37103600-8cfb-11e9-967c-7bf14e3cdf1b.png)

**Comment by xiaoxiong111** [comment]
好的学长




------------------ 原始邮件 ------------------
发件人: "763139102"<notifications@github.com>;
发送时间: 2019年6月12日(星期三) 上午10:17
收件人: "murongqimiao/DAGBoard"<DAGBoard@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [murongqimiao/DAGBoard] 推拽节点 鼠标移出 视图范围，MouseUp 事件 失效 (#5)

**Comment by 763139102** [comment]
> 好的学长
> [...](#)
> ------------------原始邮件------------------发件人：“763139102”<notifications @ github。 COM>; 发送时间：2019年6月12日（星期三）上午10:17收件人：“murongqimiao / DAGBoard”<DAGBoard@noreply.github.com>; 抄送：“已订阅”<subscribed@noreply.github.com>; 主题：Re：[murongqimiao / DAGBoard]推拽节点鼠标移出视图范围，MouseUp事件失效（[＃5](https://github.com/murongqimiao/DAGBoard/issues/5)） - 您收到此消息是因为您订阅了此主题。直接回复此电子邮件，在GitHub上查看，或将该线程静音。

那我是不是不用自己改了，等你写好了，再用

**Comment by xiaoxiong111** [comment]
这个邮件怎么乱码了 有点迷






------------------ 原始邮件 ------------------
发件人: "763139102"<notifications@github.com>;
发送时间: 2019年6月12日(星期三) 上午10:28
收件人: "murongqimiao/DAGBoard"<DAGBoard@noreply.github.com>;
抄送: "Foy。"<1304097186@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [murongqimiao/DAGBoard] 推拽节点 鼠标移出 视图范围，MouseUp 事件 失效 (#5)



 
好的学长
 ...
 ------------------原始邮件------------------发件人：“763139102”<notifications @ github。 COM>; 发送时间：2019年6月12日（星期三）上午10:17收件人：“murongqimiao / DAGBoard”DAGBoard@noreply.github.com; 抄送：“已订阅”subscribed@noreply.github.com; 主题：Re：[murongqimiao / DAGBoard]推拽节点鼠标移出视图范围，MouseUp事件失效（＃5） - 您收到此消息是因为您订阅了此主题。直接回复此电子邮件，在GitHub上查看，或将该线程静音。
  
那我是不是不用自己改了，等你写好了，再用

**Comment by 763139102** [comment]
看阿里新版了没有 ，很流畅

**Comment by murongqimiao** [comment]
> 有时间看看这个问题
不好意思最近数模组用到这个DAG了才回来看问题....  
这个问题是鼠标脱离#svg区域, 未监听mouseUp事件造成的吧~

**Comment by murongqimiao** [comment]
> 看阿里新版了没有 ，很流畅

阿里PAI更新了?  wow!

**Comment by murongqimiao** [comment]
now we resolved this problem in lasted version.
现在鼠标移出画布,自动失去所有事件状态.
